package ink.cyz.use.music;


// Generated by Selenium IDE

import cn.hutool.core.io.FileUtil;
import cn.hutool.http.HttpUtil;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class MusicDownloadBySelenium {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    public void downloadFile(String src,String fileName){
        try {
            URL url = new URL(src);
            URLConnection connection = url.openConnection();
            InputStream is = connection.getInputStream();
            FileOutputStream fos = new FileOutputStream(fileName);
            byte[] buffer = new byte[1024];
            int length = 0;
            int byteRead = 0;
            while ((byteRead = is.read(buffer)) != -1){
                fos.write(buffer,0,byteRead);
            }
            fos.close();
            is.close();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
    public void downloadMusicFromQQ_or_Lanwuzhe(String url){
        setUp();
        if (url.contains("lanwuzhe"))
            downloadByLanwuzhe(url);
        else if (url.contains("yqq")) {
            int downloadCount = 0;
            while (downloadCount<5 && downloadByQQ(url) == false) {
                System.out.printf("QQ音乐重新下载: 第%d次",downloadCount);
                downloadCount++;
            }
        }
        else
            System.out.println("该音乐不支持下载!");
        tearDown();
    }
    public void setUp() {
            FirefoxOptions firefoxOptions = new FirefoxOptions();
            firefoxOptions.addArguments("-headless");
            driver = new FirefoxDriver(firefoxOptions);
            js = (JavascriptExecutor) driver;
            vars = new HashMap<String, Object>();
        }
    public void tearDown() {
            driver.quit();
        }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    public boolean downloadByQQ(String url) {
//        driver.get("https://y.qq.com/n/yqq/song/232880789_num.html?ADTAG=h5_playsong&no_redirect=1");
        driver.get(url);
        String title = driver.getTitle().split(" ")[0];
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.linkText("播放")).click();
        vars.put("win8906", waitForWindow(2000));
        driver.switchTo().window(vars.get("win8906").toString());
        WebDriverWait wait = new WebDriverWait(driver, 5);
        try {
            wait.until(
                    new ExpectedCondition<Boolean>() {
                        public Boolean apply(WebDriver driver) {
                            return driver.findElement(By.cssSelector("#h5audio_media")) != null;
                        }
                    }
            );
        } catch (Exception e) {
            System.out.println("QQ音乐下载失败,请查看截图: d:\\music\\"+title+".png");
            File file= ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
            File screenShot = new File("d:\\music\\"+title+".png");
            if (screenShot.exists())
                screenShot.delete();
            FileUtil.copyFile(file, screenShot);
            return false;
        }
        String src = driver.findElement(By.cssSelector("#h5audio_media")).getAttribute("src");
        HttpUtil.downloadFile(src, "d:\\music\\"+title);
        System.out.println(src);
        return true;
    }
    public void downloadByLanwuzhe(String url) {
        driver.get(url);
        String title = driver.getTitle().split(" ")[0];
        WebDriverWait wait = new WebDriverWait(driver, 5);
        try {
            wait.until(
                    new ExpectedCondition<Boolean>() {
                        public Boolean apply(WebDriver driver) {
                            return driver.findElement(By.cssSelector("#audio")) != null;
                        }
                    }
            );
        } catch (Exception e) {
            System.out.println("下载失败");
            File file= ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
            FileUtil.copyFile(file,new File("d:\\"+title+".png"));
        }
        String src = driver.findElement(By.cssSelector("#audio")).getAttribute("src");
        System.out.println(src);
        downloadFile(src,"d:\\music\\"+title);
    }
    public static void main(String[] args) {
        MusicDownloadBySelenium t= new MusicDownloadBySelenium();
//        t.downloadByLanwuzhe("http://m.lanwuzhe.com/app/audio/audio.html?id=2125");
        String s = "https://y.qq.com/n/yqq/song/105395570_num.html?ADTAG=h5_playsong&no_redirect=1";
        t.downloadMusicFromQQ_or_Lanwuzhe(s);
    }
}

