package ink.cyz.use.music;


// Generated by Selenium IDE

import cn.hutool.Hutool;
import cn.hutool.core.io.FileUtil;
import cn.hutool.http.HttpUtil;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class MusicDownloadBySelenium {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    public static void main(String[] args) {
        MusicDownloadBySelenium t= new MusicDownloadBySelenium();
        String[] urls = {
            ""
        };
        for(String s:urls){
            t.downloadMusicFromQQ_or_Lanwuzhe(s);
        }
    }
    public void downloadFile(String src,String fileName){
        try {
            URL url = new URL(src);
            URLConnection connection = url.openConnection();
            InputStream is = connection.getInputStream();
            FileOutputStream fos = new FileOutputStream(fileName);
            byte[] buffer = new byte[1024];
            int length = 0;
            int byteRead = 0;
            while ((byteRead = is.read(buffer)) != -1){
                fos.write(buffer,0,byteRead);
            }
            fos.close();
            is.close();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
    public void downloadMusicFromQQ_or_Lanwuzhe(String url){
        setUp();
        if (url.contains("lanwuzhe"))
            downloadByLanwuzhe(url);
        else if (url.contains("yqq")) {
            int downloadCount = 0;
            while (downloadCount<2 && downloadByQQ(url) == false) {
                System.out.printf("QQ音乐重新下载: 第%d次",downloadCount);
                downloadCount++;
            }
        }
        else
            System.out.println("该音乐不支持下载!(可能存在页面跳转,请重新获取网址)");
        tearDown();
    }
    public void setUp() {
            FirefoxOptions firefoxOptions = new FirefoxOptions();
            firefoxOptions.addArguments("-headless");
            driver = new FirefoxDriver(firefoxOptions);
            js = (JavascriptExecutor) driver;
            vars = new HashMap<String, Object>();
        }
    public void tearDown() {
            driver.quit();
        }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    public boolean downloadByQQ(String url) {
        driver.get(url);
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.manage().deleteAllCookies();
        String cookies = "RK=bQosVPdpaB; ptcz=bae360d43dee36c5e342195b1d044de2d62f1b3f169e98011aca603abf2876bd; pgv_pvi=4262318080; pgv_pvid=906440610; yq_index=1; tvfe_boss_uuid=bd47be9debb03f73; o_cookie=421248827; pac_uid=1_421248827; userAction=1; luin=o0421248827; lskey=00010000aebe1d87365883e9e78a213f4f0111fb795d290f2b75c3dc9efeeac1fa2fdb271e9d5227d723e707; p_luin=o0421248827; p_lskey=00040000012645027ed3bee6f60f48ca9730ddc6741d879b574f4b01534479646a14f211d91de7c7b5ec5f26; pgv_si=s986231808; _qpsvr_localtk=0.9108283522744863; pt4_token=qWBE86F5TMNQFBkVS*VPNbAsW9D3*ShfXyRgUoxVZzk_; yq_playschange=0; yq_playdata=; qqmusic_fromtag=66; player_exist=1; yplayer_open=0; uin=o0421248827; skey=@xZ8hSoBuA; ptisp=cm; p_uin=o0421248827; p_skey=4J6YC5tGKL39MQ-mF-L5aC6gNEtiHHSfBqrjdws5mLU_; yqq_stat=0; pgv_info=ssid=s1299368136; ts_last=y.qq.com/n/yqq/song/202650977_num.html; ts_refer=ADTAGh5_playsong; ts_uid=135682512";
        String[] cks = cookies.split("; ");
        for (String ck : cks){
            if (ck.split("=").length<2)continue;
            driver.manage().addCookie(new Cookie(ck.split("=")[0],ck.split("=")[1]));
        }

        String title = driver.getTitle().split(" ")[0];
        vars.put("window_handles", driver.getWindowHandles());


        driver.findElement(By.linkText("播放")).click();

        vars.put("win8906", waitForWindow(2000));
        driver.switchTo().window(vars.get("win8906").toString());
        WebDriverWait wait = new WebDriverWait(driver, 5);
        try {
            wait.until(
                    new ExpectedCondition<Boolean>() {
                        public Boolean apply(WebDriver driver) {
                            return driver.findElement(By.cssSelector("#h5audio_media")) != null;
                        }
                    }
            );
        } catch (Exception e) {
            System.out.println("QQ音乐下载失败,请查看截图: d:\\music\\"+title+".png");
            File file= ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
            File screenShot = new File("d:\\music\\"+title+".png");
            if (screenShot.exists())
                screenShot.delete();
            FileUtil.copyFile(file, screenShot);
            return false;
        }
        String src = driver.findElement(By.cssSelector("#h5audio_media")).getAttribute("src");
        System.out.println(src);
        HttpUtil.downloadFile(src, "d:\\music\\"+title);
        System.out.println(src);
        return true;
    }
    public void downloadByLanwuzhe(String url) {
        driver.get(url);
        WebDriverWait wait = new WebDriverWait(driver, 5);
        try {
            wait.until(
                    new ExpectedCondition<Boolean>() {
                        public Boolean apply(WebDriver driver) {
                            return driver.findElement(By.cssSelector("#audio")) != null;
                        }
                    }
            );
        } catch (Exception e) {
            System.out.println("下载失败");
            File file= ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
            FileUtil.copyFile(file,new File("d:\\"+"蓝舞者下载失败"+".png"));
        }
        String title = driver.getTitle();
        String src = driver.findElement(By.cssSelector("#audio")).getAttribute("src");
        System.out.println(src);
        downloadFile(src,"d:\\music\\"+title);
    }

}

